### ISSUE TITLE
Any chance of using without expo?

### ISSUE THREAD

**Issue by CommanderRedYT** [pchmn/expo-material3-theme#13]
Hi there,

is there any chance that this project could be made compatible with non-expo react-native projects?

**Comment by pchmn** [comment]
Hi,

You can use it in a bare react-native project if you have expo modules installed (https://docs.expo.dev/bare/installing-expo-modules/), but I suppose you're saying without expo at all.

Sadly for now it is not planned to make this project compatible outside of expo modules

**Comment by CommanderRedYT** [comment]
I suppose as long as I don't have to change other things in the app and can continue working on it like before, using expo like this will be fine. You think it might make sense to refer to this guide in readme for projects using react-native directly?

**Comment by pchmn** [comment]
Normally yes, it shouldn't impact your project to much.

And it is already in the readme, here: https://github.com/pchmn/expo-material3-theme?tab=readme-ov-file#installation-in-bare-react-native-projects 🙂

**Comment by CommanderRedYT** [comment]
Oh, I must have missed that :sweat_smile:
But yea, will follow that guide, thanks!
