### ISSUE TITLE
Add missing Material 3 colors

### ISSUE THREAD

**Issue by PalmDevs** [pchmn/expo-material3-theme#6]
M3 has some color tokens which doesn't seem exist in this library. The colors that I've found to be missing are:
- Surface dim
- Surface bright
- Surface container lowest
- Surface container low
- Surface container
- Surface container high
- Surface container highest
- Surface tint

Is it possible to add all of these? Thank you.
#### [**M3 color tokens table**](https://m3.material.io/styles/color/the-color-system/tokens#7fd4440e-986d-443f-8b3a-4933bff16646)

**Comment by pchmn** [comment]
@PalmDevs  [v1.2.0](https://github.com/pchmn/expo-material3-theme/releases/tag/v1.2.0) has just been released with these new color tokens

**Comment by PalmDevs** [comment]
> @PalmDevs  [v1.2.0](https://github.com/pchmn/expo-material3-theme/releases/tag/v1.2.0) has just been released with these new color tokens 

Thank you so much! 🙏🏻
